# Generated by Django 6.0.5 on 2026-05-29 04:43

import useraccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_alter_user_country_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='null', null=True, upload_to=useraccount.models.User.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
